site_name: Retro Game Engine
site_description: A retro-style game engine built with Pygame
repo_url: https://github.com/ahmed5145/retro_game_engine
repo_name: ahmed5145/retro_game_engine

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
    - Overview: tutorials/README.md
    - Platformer: tutorials/platformer.md
  - Guides:
    - FAQ: guides/faq.md
    - Migration: guides/migration.md
    - Best Practices: guides/best-practices.md
    - Performance: guides/performance.md
    - Troubleshooting: guides/troubleshooting.md
  - API Reference:
    - Overview: api/index.md
    - Core:
      - Game Loop: api/game_loop.md
      - Input: api/input.md
      - Window: api/window.md
      - Vector2D: api/vector2d.md
    - Graphics:
      - Sprite: api/sprite.md
      - Sprite Renderer: api/sprite_renderer.md
