name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
        close-pr-message: 'This PR was closed because it has been stalled for 5 days with no activity.'
        days-before-stale: 30
        days-before-close: 5
        exempt-issue-labels: 'pinned,security,bug,enhancement'
        exempt-pr-labels: 'pinned,security,work-in-progress'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
